### ISSUE TITLE
Formato para beneficios en preselección

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#14]
Implementar formato para beneficios en estado de preselección siguiendo la propuesta del Mockup

**Comment by ismaeluct2013** [comment]
esta casi terminado, debo hacer una revisión de como se adapta y ver quizás agregar otra rejilla general en este caso dentro de los beneficios.

**Comment by ismaeluct2013** [comment]
se dejo lo mas adaptable posible en cuanto a la cantidad de las becas  y que los recuadros de los colores quede al costado, aunque si es necesario se puede revisar una vez mas.
