### ISSUE TITLE
Modificar estructura de CSS para colores

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#15]
Modificar CSS con nuevos tags para los bloques y recuadros utilizando la siguiente propuesta de nombres:

```
.barraRUT
.bloqueInformacion
.bloqueInformacion.informacionDestacada
.bloqueInformacion.datosPostulante
.bloqueInformacion.misBeneficios
.recuadroProceso
.recuadroProceso.primerAno
.recuadroProceso.complementarias
.recuadroProceso.superiores
.recuadroBeneficio
.recuadroBeneficio.asignado
.recuadroBeneficio.noAsignado
.recuadroBeneficio.cumpleRequisitos
.recuadroBeneficio.noCumpleRequisitos
```

Se define un color default para el recuadro (P.Ej. recuadroProceso) y sólo en caso de que se desee especificar el color para casos particulares se utiliza una clase adicional (recuadroProceso primerAno).

Generar 2 alternativas de CSS de colores:  colors.css (con colores definidos en archivo compartido por mail) & colors2.css (con colores definidos en Mockup).

**Comment by ismaeluct2013** [comment]
avanzando ya estan funcionando las clases desde el css colores, revisar aun mas eso si.

**Comment by ismaeluct2013** [comment]
para cada configuracion de color nueva se agregara en este css.
