### ISSUE TITLE
Implementar contenido en popups de beneficios

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#17]
Implementar despliegue del contenido del popup de beneficios para todos los posibles estados (desplegando campos para pasos, motivos, etc ...) según modelo del mockup.

**Comment by ismaeluct2013** [comment]
se avanzo en completar el estilo y texto de estos, pero aun falta ver en todos los casos.

**Comment by elaval** [comment]
No olvidar agregar funcionalidad para desplegar "Pincha aquí para ver los pasos a seguir" y agregar link a "Beca BEA" (o Beca respectiva) en beneficios Asignados y No asignados (si los datos no incluyen "Pasos" no se debe desplegar el "Pinchar aquí ..."

![pasos no asignado](https://cloud.githubusercontent.com/assets/68602/6133930/7a307688-b155-11e4-80e4-6c1f645d9aee.png)

**Comment by ismaeluct2013** [comment]
listo para todos los casos.
