### ISSUE TITLE
Desplegar todos los campos del JSON en la página

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#2]
Mostrar toda la información del estudiante en la pagina HTML, sin preocuparse del formato todavía (mostrar todo como líneas de texto usando divs y listas cuando corresponda).

Incluir todos datos del estudiante, las becas asignadas y no asignadas, los pasos a seguir y los causas de no asignación.

En una etapa posterior vamos a preocuparnos del formato con bootstrap y del despliegue dinámico de algunos componentes de información

**Comment by ismaeluct2013** [comment]
datos mostrados.

**Comment by elaval** [comment]
Falta agregar los datos de los motivos de la no asignación para los beneficios que no fueron asignados (chequear JSOn y el Mockup).
