### ISSUE TITLE
Permitir mensajes con contenido html

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#20]

**Comment by elaval** [comment]
Angular no despliega los contenidos de texto que tengan tags html como contenido html (por seguridad).  Pero es posible configurar el despliegue del contenido de algunos tags "seguros" utilizando:

```
<div ng-bind-html="msg"></div> en vez de <div>{{msg}}</div>
```

Para esto se necesita tener incorporado el módulo ngSanitize en la aplicación.

Para hacer pruebas de html se agregó el archivo de datos 12345680.json que es una copia del 12345679.json, pero incorporanto tags <strong> de prueba en el texto.

Es necesario utilizar ng-bind-html y verificar que todos los mensajes que desplieguen texto proveniente del JSON con datos puedan desplegar contenido html.

**Comment by elaval** [comment]
JSON de ejemplo agregado en commit 8d87735d2bab7d69d94f80ead003aa96d250629b
ngSanitize agregado en commit 5973f818ef1692873d0a9ee68e5217ef0abfbe35

**Comment by ismaeluct2013** [comment]
ng-bind-html funcionando.
