### ISSUE TITLE
Agregar línea de tiempo gráfica entre etapas (instancias)

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#21]
Sugiero generar un nuevo directive (tdTimelineInstancias) que genere un elemento <svg> con el diagrama de tiempo y que tenga definido un modelo con la instancia seleccionada.

Ej

<div td-timeline-instancias ng-model="controller.atributoCorrespondiente"></div>

Que por debajo genere:
<div>
<svg><g><circle ...><line ..> ....</g></svg>
<div>

Para los browsers que no manejen <svg> mantenemos el despliegue con botones tradicionales.

Se pueden usar los tags de modernizr para desplegar/ocultar el div correspondiente en caso de que maneje/no maneje svg.

**Comment by elaval** [comment]
Cerrar cuando esté publicado el "commit" que lo implemente en el index.html ¿vale?

**Comment by ismaeluct2013** [comment]
listo en index.html
