### ISSUE TITLE
Modificar referencias de categorías/etapas a procesos/instancias

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#23]
Cambiar JSON & código para facilitar lenguaje común conmovedores de información.

Podemos dejar las "etapas" por ahora, pero probablemente debamos cambiar categorías por procesos

**Comment by elaval** [comment]
Se agregó un JSON de prueba que utiliza el atributo "procesos" en vez de "categorias".

12345678B.json

Usar este como base para cambiar el html y hacer referencia a "proceso" o "procesos" en (los atributos, variables, comentarios, CSS, ...)

**Comment by ismaeluct2013** [comment]
se modifico principalmente en archivos como index y controller, en el resto se reviso eso si cualquier referencia a categorias.
