### ISSUE TITLE
Corregir problema de formato en título para tamaño de ventana mediano

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#24]
El logo se superpone con el título en ventanas de tamaño medio

![responsive](https://cloud.githubusercontent.com/assets/68602/6079909/520fc514-ae03-11e4-841d-f073bd86ef52.png)

**Comment by ismaeluct2013** [comment]
solucionado las rejillas medianas tenia que cambiarle de 1-8-3 a 2-7-3.
