### ISSUE TITLE
Evitar que ventana popup reduzca tamaño con beneficios cerca del borde derecho 

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#25]
El desplegar el popup siempre a la derecha del recuadro de beneficios, se puede quedar sin espacio suficiente.  Se sugiere utilizar un placement "auto".

![popup placement](https://cloud.githubusercontent.com/assets/68602/6079926/825da7ea-ae03-11e4-9649-b77a941e37fd.png)

**Comment by ismaeluct2013** [comment]
le puse la opción auto, mejora bastante ya utiliza la pantalla a su ancho cuando son dispositivos pequeños
