### ISSUE TITLE
Cerrar los popups de beneficios al cambiar de foco

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#27]
Actualmente se pueden abrir múltiples ventanas de beneficios que quedan montadas una sobre otra.

Se deben cerrar las ventanas cuando se haga click en otra parte de la ventana principal (P.ej. al hacer click en otro beneficio)

**Comment by ismaeluct2013** [comment]
aun en depuración

**Comment by elaval** [comment]
Hice un cambio parcial para que ocultara los otros popovers 

```
        //Ocultar todos los popovers excepto el mío
        $('.popover').each(function() {
            if ($(this).attr("id") != popover.$tip.attr("id")) {
                $(this).popover('hide'); 
            }
        }); 
```

Pero quedó pendiente el que se oculte el popover al hacer un click en otros elementos (Ej, botones de linea de tiempo)

**Comment by ismaeluct2013** [comment]
solucion tres en directive usando una "mezcla" entre las anteriores.
