### ISSUE TITLE
Utiliza el controller principal para el acordeon

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#29]
No debiera ser necesario generar un nuevo controller para el acordeón ... tratar de utilizar el controller principal

**Comment by elaval** [comment]
Sugerencia ... 

Mirando el código veo que el controller - AccordionDemoCtrl - se utiliza principalmente para mantener las variables:

oneAtATime ($scope.oneAtATime en el controller) 

y eventualmente un marcador que indica que la primera acordeón está abierta

status.isFirstOpen
  $scope.status = {
    isFirstOpen: true,
    isFirstDisabled: false
  };

Para comunicarse entre el controller y la vista existen 2 prácticas comunes:

## 1) Utilizar $scope

$scope es un "objeto" que permite acceder a las variables directamente en la vista (Ej. oneAtATime) y que puede incluirse dentro de las dependencias del Controller para tener acceso a él.

``` javascript
angular.module('tideApp')
.controller('AppController', ['$scope' ,function ($scope) {
  $scope.oneAtATime = true;
}
```

``` html
<div ng-controller="AppController">
< accordion close-others="oneAtATime">

```

## 2) Utilizar "variable as Controller" 

El Controller es un objeto (en estricto rigor una función pero para efectos prácticos opera como objeto) que puede tener propiedades que se acceden en su interior con a través de "this".

Para acceder al las propiedades del Controller, se puede utilizar la fórmula "variable as Controller" al especificar el controller y de esta manera generamos un alias que nos permite acceder a sus propiedades.

``` javascript
angular.module('tideApp')
.controller('AppController', ['$scope' ,function ($scope) {
  this.oneAtATime = true;
}
```

``` html
<div ng-controller="AppController as miController">
< accordion close-others="miController.oneAtATime">

```

En este proyecto estamos utilizado el alias "controller" para hacer referencia a las propiedades del controller (y así hacer explícito que es una propiedad del controller y saber donde está operando).

Sugiero que en AppController definamos un objeto en el que mantenga el estado de cada uno de los elementos del acordeón:

``` javascript
angular.module('tideApp')
.controller('AppController', ['$scope' ,function ($scope) {
  this.isOpenAccordion = {
    mensajesDestacados: true,
    datosPostulante: false,
    misBeneficios : false
  };
}
```

Y luego en el acordeón hacemos referencia a:

``` html
<accordion close-others="'true'"> // No necesitamos una variable para close-others
         <accordion-group is-open="controller.isOpenAccordion.mensajesDestacados">
         </accordion-group>
         <accordion-group is-open="controller.isOpenAccordion.datosPostulante">
         </accordion-group>
         <accordion-group is-open="controller.isOpenAccordion.misBeneficios">
         </accordion-group>
</accordion>
```

**Comment by ismaeluct2013** [comment]
utilice sugerencia 

angular.module('tideApp')
.controller('AppController', ['$scope' ,function ($scope) {
  this.isOpenAccordion = {
    mensajesDestacados: true,
    datosPostulante: false,
    misBeneficios : false
  };
}
