### ISSUE TITLE
Corregir despliegue de formato moneda

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#33]
Corregir despliegue de montos con formato moneda.  En algunos navegadores (Ej. Safari en Inglés) se despliega con decimales.

![currency](https://cloud.githubusercontent.com/assets/68602/6133789/5ad0247e-b154-11e4-8804-7c0210303c3c.png)
![currency2](https://cloud.githubusercontent.com/assets/68602/6133792/5eef53c2-b154-11e4-831b-709c4b2c6ef1.png)

Agregar formato moneda en popover

![currency3](https://cloud.githubusercontent.com/assets/68602/6133800/662ecc58-b154-11e4-9b1b-e915155bc3f8.png)

**Comment by elaval** [comment]
Puede deberse a la versión de Angular.  Yo estoy usando Angular 1.2.28 (para evitar problemas de compatibilidad con Bootstrap).  Puede que si funcione bien en 1.3 y no en 1.2.28.

**Comment by ismaeluct2013** [comment]
investigando y probando, encontré por ahí una información que decía que la solución que yo estaba utilizando era para angularjs 1.3 (yo tengo la 1.2.28 también y me funcionaba pero a mi jeje) y también daba el uso para las versiones anteriores:  .slice(0,-3).
Con esto deje de la siguiente manera:
{{(controller.data.misBeneficios.montoOtorgado | currency).slice(0,-3) }}
ya esta de esta forma en el index.html
