### ISSUE TITLE
Corregir despliegue de leyenda al tener pocos beneficios

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#35]
Mantener leyenda de beneficios en listado vertical aún con número reducido de beneficios

![leyenda mal](https://cloud.githubusercontent.com/assets/68602/6133864/e9c1b6d4-b154-11e4-9263-87b8c235ef7b.png)
![leyenda ok](https://cloud.githubusercontent.com/assets/68602/6133867/edb43d0c-b154-11e4-92b5-8976f9233db1.png)

**Comment by ismaeluct2013** [comment]
solucionado con una propuesta que se puede monitoriar para los futuros rut y datos de otros usuarios.
