### ISSUE TITLE
Tooltip en línea de tiempo de etapas debe desplegar texto completo

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#36]
El tooltip en las etapas de la "línea de tiempo" debe desplegar el texto completo que esté definido para el tooltip.

![tooltip](https://cloud.githubusercontent.com/assets/68602/6134047/4596ebcc-b156-11e4-859e-df194e121f3a.png)

**Comment by ismaeluct2013** [comment]
en el json en las etapas y sus mensajes  tooltip ejemplo  en becas complementarias:
"postulacion" : {
        "mensajeTooltip":"Mensaje tooltip postulación de Cursos Superiores ... ",

confirme que todas estos mensajes en estas escritas así con ..., lo que si solucione es que solo estaba mostrando las de primer año en las tres lineas de tiempo y arregle eso (haré el commit en un ratito de esto) y también probé con un texto mucho mas extenso que el que muestro del ejemplo y no hay problema eso si estoy viendo la forma de cambiarle el estilo a estos tooltip() para que sea como en el proyecto original.

**Comment by elaval** [comment]
Buen punto!  Modifiqué el JSON para que incluya un texto más extenso.

**Comment by elaval** [comment]
Cerramos este issue y si es necesario ajustar el formato abrimos otro más adelante
