### ISSUE TITLE
Cambiar puntero en áreas cliqueables

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#37]
Actualmente la imagen del mouse - cursor -  adquiere la forma de un punto de inserción de texto en algunos sectores cliqueables (cuadros de beneficios, etapas en la línea de tiempo).

Cambiar aun "dedo que apunta" (pointer) en los sectores cliqueables.

**Comment by ismaeluct2013** [comment]
se  puso pointer en todos las zonas ahora falta solo en la linea de tiempo (ya esta el commit) por lo mismo no cerrare el ussue hasta tener la linea de tiempo con el pointer.
