### ISSUE TITLE
Implementar links en "Postulación" y "Detalle beneficio"

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#44]
Abrir una nueva ventana al presionar botón de "Apela ..." con la página indicada en el atributo del JSON

``` json
"urlApelacion":"http://mineduc.cl",
```

![link1](https://cloud.githubusercontent.com/assets/68602/6184822/8868fcba-b35e-11e4-8f5c-542af9b6c7af.png)

No desplegar el botón si el url no se define o está vacío.

También abrir una nueva ventana con el detalle del beneficio cuando se haga click en el link en el popover del respectivo beneficio.
![link2](https://cloud.githubusercontent.com/assets/68602/6184875/51bf0cd0-b35f-11e4-9e47-fec1d5d3e2c1.png)

El JSON no ha incluido el atributo correspondiente al link, pero debe agregarse (como urlBeneficio) en:

```
                        "beneficios": [
                            {
                                "sigla":"BVP",
                                "nombre":"Beca Vocacion de Profesor",
                                "estado":"cumpleRequisitos",
                                "pasos":"",
                                "urlBeneficio":"http://portal.becasycreditos.cl/benecicios/bvp"
                            },
```

No desplegar el link si el url no se define o está vacío

**Comment by elaval** [comment]
Se agregó urlBeneficio en JSON  en commit 18589e24ca84e8ef679e036f84dc4e6c4bd979a2

**Comment by ismaeluct2013** [comment]
declare la siguiente en controller para ver si mostrar o no:
var isUndefined = function(val) {
  if(angular.isUndefinedOrNull(val))
    return true;

return false;
};

**Comment by elaval** [comment]
Creo que basta con indicar 

```
ng-show="categoriaBeneficio.urlApelacion"
```

Si la propiedad no esta definida (o es nula) se interpreta como false y si esta definida como true (pero hay que probarlo)
