### ISSUE TITLE
Popover está desplegando mensajes estáticos

### ISSUE THREAD

**Issue by elaval** [TIDE-Chile/resultados#48]
El popover asociado a los beneficios está desplegando mensajes estáticos asociados a los motivos para la no asignación de beneficios o el no cumplimiento de requisitos.

Estos mensajes deben provenir del archivo JSON

**Comment by ismaeluct2013** [comment]
esta parte la cambie en beneficios template pero estoy cambiando tambien para que los mensajes de tipo html los muestre bien, en eso me estoy demorando, intento utilizar trustAsHtml ya que ng-bind-html al utilizar asi nomas tiene problemas con caracteres (ñ %, tildes).

**Comment by elaval** [comment]
Ismael ... yo hice algunas pruebas con ng-bind-html y me mostraba bien los textos con tildes

Por ejemplo para los "Mesnajes generales"

```
            <div ng-repeat="(i, msg) in controller.data.mensajesDestacados">
              <div class="col-xs-2 col-md-1 col-lg-1">
                <p class="subtitulo" style="color:blue;text-align:right;"><i class="glyphicon glyphicon-exclamation-sign"></i></p>
              </div>
              <div class="col-xs-10 col-md-11 col-lg-11">
                <p> Mensaje General {{$index+1}}: <span ng-bind-html="msg"></span></p>
              </div>
            </div>
```

![html](https://cloud.githubusercontent.com/assets/68602/6305437/3b204a80-b8f9-11e4-9763-e11e38c7467e.png)

Dale una vuelta a ver si logras hacerlo funcionar ... intuyo que el ng-bind-html puede ser una solución más limpia.

**Comment by ismaeluct2013** [comment]
ahora si funciona, solo me falta hacerlo con todos los mensajes :D.

**Comment by ismaeluct2013** [comment]
en etapa preseleccion tenemos lo siguiente:
![2](https://cloud.githubusercontent.com/assets/6326779/6306496/cf346102-b912-11e4-95ce-68bde61d17be.PNG)

Donde las becas que noCumpleRequicitos, la primera tiene motivos.descripcion y el resto tiene motivos.contenido.

probocando el siguiente problema:
- una si muestra bien el contenido ya que al ir a buscar digo que muestre  motivos.descripcion:

![5](https://cloud.githubusercontent.com/assets/6326779/6306563/3efa9768-b913-11e4-92fb-635decadabed.PNG)
- pero en el resto no ya que tienen en json motivos.contenido:

![3](https://cloud.githubusercontent.com/assets/6326779/6306542/16a0c6de-b913-11e4-9e1c-a152fd0626f7.PNG)

Pero motivos.descripcion esta solo para la primera beca que no cumple los requisitos en Primer año y en preseleccion. Entonces yo sugiero que la dejemos como el resto motivos.contenido. Que dice usted?

**Comment by ismaeluct2013** [comment]
para sacar el mensaje estatico en el json 12345680 cambie de motivos.descripcion a motivos.contenido, como el resto de los mensajes, si dejamos hace hay que hacer ese cambio en los demas json.
